name: freecad-deps-core24
base: core24
adopt-info: version
summary: Dependencies for FreeCAD snaps
description: |
  - OCCT
  - GMSH

grade: stable
confinement: strict

parts:
  version:
    plugin: nil
    build-packages:
      - git
    override-build: |
      cd "${CRAFT_PROJECT_DIR}"
      git_hash=$(git rev-parse --short=8 HEAD)
      craftctl set version="${git_hash}"

  occt:
    plugin: cmake
    source: https://gitlab.com/blobfish/occt.git
    source-branch: V7_8_0_BF
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=${CRAFT_STAGE}/usr
      - -DUSE_TBB:BOOL=off
      - -DUSE_VTK:BOOL=off
      - -DUSE_FREEIMAGE:BOOL=on
      - -DBUILD_RELEASE_DISABLE_EXCEPTIONS:BOOL=off
      - -DUSE_RAPIDJSON:BOOL=on
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE
      - -D3RDPARTY_TBB_LIBRARY_DIR=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -D3RDPARTY_TBBMALLOC_LIBRARY_DIR=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-packages:
      - libfreeimage-dev
      - libfreetype6-dev
      - tcl-dev
      - tk-dev
      - libtbb-dev
      - libgl-dev
      - rapidjson-dev
    stage-packages:
      - libtbb12
      - libtbbmalloc2
    override-build: |
      craftctl default
      find "${CRAFT_PART_INSTALL}/usr/lib/cmake" \
        -type f \
        -name "*.cmake" \
        -exec sed -i -e 's|\\${OCCT_INSTALL_BIN_LETTER}||g' {} \;
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    prime:
      -  -usr/share/opencascade

  gmsh: # FEM
    after: [occt]
    plugin: cmake
    source: https://gitlab.onelab.info/gmsh/gmsh.git
    source-tag: gmsh_4_13_1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=${CRAFT_STAGE}/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_BUILD_DYNAMIC=1
      - -DENABLE_MED=0
      - -DENABLE_FLTK=0
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
  cleanup:
    after: [occt, gmsh]
    plugin: nil
    override-prime: |
      set -eux
      for cruft in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$cruft
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
