name: freecad-deps-core24
base: core24
adopt-info: version
summary: Dependencies for FreeCAD snaps
description: |
  - OCCT
  - GMSH

grade: stable
confinement: strict

parts:
  version:
    plugin: nil
    build-packages:
      - git
    override-build: |
      cd "${CRAFT_PROJECT_DIR}"
      git_hash=$(git rev-parse --short=8 HEAD)
      craftctl set version="${git_hash}"

  occt:
    plugin: cmake
    source: https://gitlab.com/blobfish/occt.git
    source-branch: V7_8_0_BF
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=${CRAFT_STAGE}/usr
      - -DUSE_TBB:BOOL=off
      - -DUSE_VTK:BOOL=off
      - -DUSE_FREEIMAGE:BOOL=on
      - -DBUILD_RELEASE_DISABLE_EXCEPTIONS:BOOL=off
      - -DUSE_RAPIDJSON:BOOL=on
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE
      - -D3RDPARTY_TBB_LIBRARY_DIR=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -D3RDPARTY_TBBMALLOC_LIBRARY_DIR=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-packages:
      - libfreeimage-dev
      - libfreetype6-dev
      - tcl-dev
      - tk-dev
      - libtbb-dev
      - libgl-dev
      - rapidjson-dev
    stage-packages:
      - libtbb12
      - libtbbmalloc2
    override-build: |
      craftctl default
      find "${CRAFT_PART_INSTALL}/usr/lib/cmake" \
        -type f \
        -name "*.cmake" \
        -exec sed -i -e 's|\\${OCCT_INSTALL_BIN_LETTER}||g' {} \;
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    prime:
      -  -usr/share/opencascade

  gmsh: # FEM
    after: [occt]
    plugin: cmake
    source: https://gitlab.onelab.info/gmsh/gmsh.git
    source-tag: gmsh_4_13_1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=${CRAFT_STAGE}/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_BUILD_DYNAMIC=1
      - -DENABLE_MED=0
      - -DENABLE_FLTK=0
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR

  elmer: # FEM
    after: [occt]
    plugin: cmake
    source: https://github.com/ElmerCSC/elmerfem.git
    source-branch: devel
    override-build: |
      craftctl default
      # Create a symlink to make the infinipath library discoverable by OpenMPI, only on amd64
      # This library is not available in other architectures (e.g. arm64)
      if [ "$CRAFT_ARCH_BUILD_FOR" = amd64 ]; then
        mkdir -p $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
        ln -sf ../libpsm1/libpsm_infinipath.so.1.16 $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpsm_infinipath.so.1
      fi
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=${CRAFT_STAGE}/usr # Use OCCT from this same snap
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_MPI:BOOL=TRUE
      - -DWITH_OpenMP:BOOL=TRUE
      - -DWITH_ElmerIce:BOOL=TRUE
      - -DELMER_SOLVER_HOME=/usr/share/elmersolver
      - -DWITH_MUMPS:BOOL=TRUE
      - -DWITH_HYPRE:BOOL=TRUE
      - -DWITH_LUA:BOOL=TRUE
      - -DWITH_MATC:BOOL=TRUE
      - -DWITH_ELMERGUI:BOOL=FALSE
      - -DWITH_OCC:BOOL=TRUE # Can now be enabled as it will find the OCCT part
      - -DWITH_VTK:BOOL=FALSE
      - -DWITH_PARAVIEW:BOOL=FALSE
    build-packages:
      - build-essential
      - cmake
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - libmumps-dev
      - libparmetis-dev
      - libmetis-dev
      - libhypre-dev
      - liblua5.1-0-dev
    stage-packages:
      - libblas3
      - liblapack3
      - libopenmpi3t64
      - libmumps-5.6t64
      - libparmetis4.0
      - libmetis5
      - libhypre-2.28.0
      - liblua5.1-0
      - on amd64: [libpsm-infinipath1]
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    prime:
      # Exclude all build-time binaries by default.
      - -usr/bin/*

      # --- Explicitly keep the required Elmer executables ---
      - usr/bin/ElmerGrid
      - usr/bin/ElmerSolver
      - usr/bin/ElmerSolver_mpi
      - usr/bin/elmerf90
      - usr/bin/matc
      - usr/bin/Mesh2D
      - usr/bin/ViewFactors

      # --- Explicitly keep the required OpenMPI runtime executables ---
      # These are needed for MPI initialization and job launching.
      - usr/bin/orterun
      - usr/bin/orted
      - usr/bin/ompi_info
      # Keep the MPI wrapper compiler scripts, as they are sometimes called by other tools.
      - usr/bin/mpicc.openmpi
      - usr/bin/mpic++.openmpi
      - usr/bin/mpicxx.openmpi
      - usr/bin/mpifort.openmpi
      - usr/bin/opal_wrapper

      # --- Exclude development, documentation, and static files ---
      - -usr/include/*
      - -usr/lib/cmake/*
      - -usr/lib/pkgconfig/*
      - -usr/share/doc/*
      - -usr/share/man/*
      - -usr/share/info/*
      - -usr/lib/**/*.a

      # Keep the Elmer-specific data files.
      - usr/share/elmersolver/*

  cleanup:
    after: [occt, gmsh, elmer]
    plugin: nil
    override-prime: |
      set -eux
      for cruft in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$cruft
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
